apiVersion: v1
kind: Service
metadata:
  name: crud-service
  namespace:  {{ .Values.namespace }}
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: load-balancer-port
    prometheus.io/scrape: "true"
spec:
  selector:
    app: crud
  ports:
    - name: load-balancer-port
      protocol: TCP
      port: {{ .Values.crud.service.port }}
      targetPort: web 
  type: ClusterIP