// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {

  postman[Request]({
    name: "DeleteUser",
    id: "6ceaa94d-8bd4-45b4-8240-9ab500d1722f",
    method: "DELETE",
    address: "http://arch.homework/api/v1/user/1",
    post(response) {
      pm.test("Status code is 20X", function() {
        pm.expect(pm.response.code).to.be.oneOf([200,204]);
      });
    }
  });

  postman[Request]({
    name: "CreateUser",
    id: "d651ac35-a306-4054-8618-0348c7f256d4",
    method: "POST",
    address: "http://arch.homework/api/v1/user",
    data:
      '{\r\n\t"id": 1,\r\n\t"username": "johndoe589",\r\n\t"firstName": "Johny",\r\n\t"lastName": "English",\r\n\t"email": "bestjohn@doe.com",\r\n\t"phone": "+71002003040"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "GetUser",
    id: "dfad962b-35e8-406a-af34-873de66e09ae",
    method: "GET",
    address: "http://arch.homework/api/v1/user/1",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "UpdateUser",
    id: "273b5c43-1e19-4131-9375-b96e5705f09f",
    method: "PUT",
    address: "http://arch.homework/api/v1/user/1",
    data:
      '{\r\n\t"id": 1,\r\n\t"username": "johndoe589",\r\n\t"firstName": "John",\r\n\t"lastName": "Does",\r\n\t"email": "bestjohn@doe.com",\r\n\t"phone": "+81002003041"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });





  
}
