apiVersion: batch/v1
kind: Job
metadata:
  name: crud-migration-job
  namespace:  {{ .Values.namespace }}
spec: 
  backoffLimit: 0
  template:
    metadata:
      name: crud-migration-job-pod
    spec:
      restartPolicy: Never
      initContainers:
      - name: check-db-ready
        image: postgres:11
        command: ["sh", "-c", "until pg_isready -U $(DB_USER) -h $(DB_HOST) -p 5432; do echo $(DB_USER), $(DB_HOST) waiting for database; sleep 2; done;"]
        env:
        - name: DB_USER              
          valueFrom:
            secretKeyRef:
              name: postgres-secret           
              key: POSTGRES_USER
        envFrom:
        - configMapRef:
            name: crud-config
      containers:
      - name: crud-migration
        image: humokobil/crud_migration:v1
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret           
              key: POSTGRES_USER 
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret 
              key: POSTGRES_PASSWORD
        envFrom:
          - configMapRef:
              name: crud-config
          - secretRef:
              name: postgres-secret
      