apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  PGDATA: /var/lib/postgresql/data/k8s