kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pv_dockerd.name }}-claim
  namespace:  {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi