apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace:  {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.pass }}